# 宣告使用 /bin/bash
#!/bin/bash

i=10

while [ $i -le 2000 ]
do
  echo Number: $i

echo "=== Initialize kafka topics === "
# wait some time for deletion
/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=39671:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar Initialize

echo "=== open validators & balancers === "
/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=39943:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar validator_maxPoll $i &

/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=39943:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar validator_maxPoll $i &

/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=39943:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar validator_maxPoll $i &

/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=34193:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar Balancer_maxPoll $i &

/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=34193:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar Balancer_maxPoll $i &

/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=34193:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar Balancer_maxPoll $i &
sleep 60
# wait some time for rebalance

echo "=== input data === "
/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=32785:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar sourceProducer_random 3 10000 &
sleep 300
pkill -f 'automaton-1.11-8.jar'

echo "=== consume sort and write to csv === "
/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=37217:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar consume_timestamp 10000


/usr/lib/jvm/java-11-amazon-corretto/bin/java -javaagent:/home/yooouuuuuuu/idea-IC-221.5921.22/lib/idea_rt.jar=39309:/home/yooouuuuuuu/idea-IC-221.5921.22/bin -Dfile.encoding=UTF-8 -classpath /home/yooouuuuuuu/IdeaProjects/kafka/FISC_payment/target/classes:/home/yooouuuuuuu/.m2/repository/org/apache/kafka/kafka-clients/3.2.0/kafka-clients-3.2.0.jar:/home/yooouuuuuuu/.m2/repository/com/github/luben/zstd-jni/1.5.2-1/zstd-jni-1.5.2-1.jar:/home/yooouuuuuuu/.m2/repository/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar:/home/yooouuuuuuu/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/yooouuuuuuu/.m2/repository/com/github/javafaker/javafaker/1.0.2/javafaker-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/yooouuuuuuu/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23-android.jar:/home/yooouuuuuuu/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar:/home/yooouuuuuuu/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar sort_timestamp 3 10000 $i




  let "i+=10" 
done









